Luu
binamp/wolox-menard pull request #3
Opened 2020-03-30 17:36 UTC by LuPradenas

Realice el maquetado de las secciones Livery services, Polo lessons, Contact Us y el Footer.

2020-03-31 21:55 UTC, JoniMujica approved these changes

2020-04-02 18:59 UTC, MMarussi requested changes
Buen trabajo! Es un PR grande asi que hay varios detalles que corregir, pero no es nada groso. Va a quedar :ok_hand: 

Algunas cosas que marqué sólo una vez pero estaría bueno que revises los archivos y lo cambies donde lo encuentres:
- Componentes de clase que se pueden definir con function
- Identado tanto en archivos .js como en .scss
- Espaciado tanto en archivos .js como en .scss
- Líneas vacías de más (o faltantes)
- Agregar línea vacía al final del archivo si es que no la tiene
- Usar clases para asignar estilos en vez de usar los selectores de html

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +
Estas líneas en blanco no son necesarias, así que se pueden borrar

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +              </div>
Un part de detallitos acá, pero más que nada para mantener la consistencia:
- Tener en cuenta los espaciados
- Tener en cuenta la identación
```suggestion
  <div className={styles.row2}>
    <img className={styles.imagen2} src={redes} alt="redes" />
    <label style={{ width: "160px" }}>+44 (0) 1865 600 448</label>
    <label style={{ width: "160px" }}>info@mendardpolo.com</label> 
  </div>
```

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +class Fooster extends React.Component {
Cuidado que dice **Fooster** en vez de **Footer**

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +     <div className={styles.containerbody}>
A partir de este `<div>` incluyendolo, todo debería estar identado dentro de `<footer>`, recuerden definir en equipo como van a identar el proyecto (cualquier cosa pueden revisar el documento de [estandarización](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro/edit#heading=h.beabsnaglgf7) para ver como hacerlo) y mantengan la consistencia!

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +
Esta también

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +export default Fooster;
Acá es necesario agregar una línea en blanco al final del archivo.

Si mirás los cambios que marca git puede ser que algunos archivos tengan el siguiente símbolo en la línea final:
![Screenshot from 2020-03-27 11-32-37](https://user-images.githubusercontent.com/11763032/78157235-1d6ce600-7416-11ea-8765-704fe3ccbb99.png)

Eso quiere decir que el archivo no tiene una línea vacía al final, por lo general se agrega una línea en blanco al final de todos los archivos para indicar el fin del mismo.

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/styles.module.scss
> +footer{
Faltó un espacio entre footer y {
```suggestion
footer {
```

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/styles.module.scss
> +
Cuidado con tener líneas vacías dentro de una clase de scss o css, nada más debería haber líneas vacías entre clase y clase o si se está usando un pseudo-elemento dentro de la misma clase.
Por ejemplo:
```SCSS
label {
  line-height: 1.8;
  color: #C5CBD3;
  font-size: 14px;
  font-family: Roboto Slab;
}

h1 {
  font-size: 18px;
  color:#C5CBD3;
  display: flex;
  margin: 2px;

  &:after {
    ...
  }
}

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/pages/ContactUs/contactus.js
> +import Footer from '../../ Footer/footer';
Agrega una línea vacía abajo para separar imports de componente

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/pages/ContactUs/form.module.scss
> +  .boton:hover {
Esta clase podría ir anidada dentro de `.boton` de la siguiente manera:

```
.boton {
  ...

  &:hover {
    color: #FFFFFF;
  }
}
```
SASS nos provee una sintaxis más cómoda para el manejo de selectores, podés investigar más en la [documentación de sass](https://sass-lang.com/documentation/style-rules)

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/styles.module.scss
> +h1{
Es preferible que crees y uses clases como selectores en vez de selector de elemento de html.
En caso de que la misma clase se necesite en algun otro lado de la aplicación se puede reutilizar y ayuda a mantener un estándar

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/pages/ContactUs/form.module.scss
> +.containeer{
Podrías usar un nombre más descriptivo para esta clase? :sweat_smile:

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/pages/ContactUs/form.module.scss
> +.labeel{
Mismo que .containeer

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/styles.module.scss
> +.containerbody{
En lo posible intenta que las clases cuyo nombre sean mas de 1 palabra esten escritas en camelCase o snake-case asi es más fácil de leer.
Si el proyecto fue creado con **create-react-app** podes usar cualquiera de las 2 notaciones sin problema, solo que en tu archivo .js tenes que referenciar a la clase en camelCase

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/ Footer/footer.js
> +class Fooster extends React.Component {
Además, como no  están usando manejando el estado del componente ni usando alguna de las funciones del ciclo de vida de un componente de clase es preferible que este pase a ser un componente funcional, así no se cargan métodos que no se van a usar.
```suggestion
function Footer() {
```

2020-04-02 18:59 UTC, MMarussi commented on frontend/src/components/pages/ContactUs/style.module.scss
> + .contaiiner{
Mismo que containeer

2020-04-02 21:59 UTC, merged