Agus
binamp/wolox-menard pull request #4
Opened 2020-03-30 18:55 UTC by agusahumada

Realicé el maquetado de Home, especificamente la seccion de descripcion- About de Company y Our services, asi como tambien la descripcion en la pantalla de Polo Holidays. La galeria de ésta seccion está en desarrollo...

2020-03-31 21:55 UTC, JoniMujica approved these changes

2020-04-03 16:27 UTC, jmtov requested changes
¡Buen trabajo, Agus!

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/carrousel/App.js
> +function App() {
¿Para qué usas éste componente?

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/navbar/navstyle.module.scss
> +@import url("https://fonts.googleapis.com/css?family=Oswald&display=swap");
Puedes importar las fuentes en el archivo general de estilos para no tener que importarla en cada archivo donde la vayas a usar.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/navbar/navstyle.module.scss
> +.toolBarRef:hover:before {
Mantén los espacios entre las declaraciones: 
```suggestion
}

.toolBarRef:hover {
  color: rgb(217, 176, 129);
  text-decoration: none;
}

.toolBarRef::before {
  content: "";
  position: absolute;
  width: 100%;
  height: 2px;
  bottom: -3px;
  left: 0;
  background-color: rgb(217, 176, 129);
  visibility: hidden;
  transform: scaleX(0);
  transition: all 0.3s ease-in-out;
}

.toolBarRef:hover:before {
```

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/Home/ourServices.js
> +        <a href="/lessons" className={styles.link}>
Si están usando React Router, usa los componentes que React Router provee para los enlaces.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/Home/styles.module.scss
> +@import url("https://fonts.googleapis.com/css?family=Oswald&display=swap"); //Logo font.
Esto se puede mover a un archivo global de estilos también.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/Home/styles.module.scss
> +  background-color: #172437;
Recuerda usar variables SCSS o variables de CSS para los colores de la aplicación.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/Home/styles.module.scss
> +.containerTitle {
Recuerda los espacios entre declaraciones dentro de todo este archivo.
```suggestion
}

.containerTitle {
```

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/PoloHoliDays/button.js
> +function Button() {
No creo que sea necesario crear un componente para este botón. Procuraría poner este código en la pantalla donde iría el botón sin crear un componente adicional.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/PoloHoliDays/styles.module.scss
> +@import url("https://fonts.googleapis.com/css?family=Oswald&display=swap"); //Logo font.
Recuerda el comentario sobre importar las fuentes en diferentes archivos. Intenta importarlas en un solo archivo global.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/PoloHoliDays/styles.module.scss
> +  color: #d9b081;
Ten en cuenta lo de las variables de colores acá también.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/PoloHoliDays/styles.module.scss
> +  background-color: #232f41;
Y acá.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/PoloHoliDays/styles.module.scss
> +  border: 1px solid #d9b081;
Y acá.

2020-04-03 16:27 UTC, jmtov commented on frontend/src/components/pages/PoloHoliDays/travel.js
> +
No dejes espacios de más en JSX.

2020-04-03 18:30 UTC, merged